name: flow_ui_cell
description: Flow UI Cell for CBS - renders "Flow" centered with modern styling
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cbs_sdk:
    path: ../../../../../framework/shared_cells/dart/cbs_sdk
  bus_monitor_cell:
    path: ../bus_monitor
  flow_text_cell:
    path: ../flow_text

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.7
