[package]
name = "body"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "body"
path = "src/main.rs"

[dependencies]
body_core = { path = "../body_core" }
body_bus = { path = "../body_bus" }
tokio = { workspace = true }
serde_json = { workspace = true }
