name: cbs_sdk
description: CBS (Cell Body System) Dart SDK for direct NATS client integration
version: 1.0.0

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  uuid: ^4.0.0

dev_dependencies:
  test: ^1.24.0
  lints: ^2.1.0

topics:
  - cbs
  - nats
  - messaging
  - microservices
