name: flow_ui_cell
description: Flow UI Cell for CBS - renders "Flow" centered with modern styling
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cbs_sdk:
    path: ../../../../shared_cells/dart/cbs_sdk

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
