[package]
name = "io_prompt_name_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
body_core = { path = "../../../../body_core" }
serde_json = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }
