[package]
name = "body_core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
serde_yaml = "0.9"

[dev-dependencies]
tempfile = "3.8"
