# Agent OS Configuration

# Refer to the official Agent OS documentation at:
# https://buildermethods.com/agent-os

agent_os_version: 1.4.1

agents:
  claude_code:
    enabled: false
  cursor:
    enabled: true

project_types:
  default:


  # type_a:
  #   instructions: ./cbs-agent/project_types/type_a/instructions
  #   standards: ./cbs-agent/project_types/type_a/standards

  # type_b:
  #   instructions: ./cbs-agent/project_types/type_b/instructions
  #   standards: ./cbs-agent/project_types/type_b/standards

default_project_type: default
