name: Rust CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: fmt
        run: |
          cargo fmt --all -- --check
      - name: clippy
        run: |
          cargo clippy --workspace --all-features -- -D warnings
      - name: test
        run: |
          cargo test --workspace --all-features --no-fail-fast


